# Generated by Django 5.1.3 on 2025-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(default=None, max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
