# Generated by Django 5.1.3 on 2025-07-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loging',
            name='user_id',
            field=models.EmailField(max_length=254),
        ),
    ]
