# Generated by Django 5.2.4 on 2025-07-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_loging_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='endangered_species_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/image/endangered_species_image')),
                ('heading', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='audio/')),
                ('species_type', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
