# Generated by Django 5.2.4 on 2025-07-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback_idea_pledge_subscriber_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='endangered_species_data',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.DeleteModel(
            name='Pledge',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
